name: Check notification

on:
  push: {}
  release: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4

    - name: Python einrichten
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Hier die gewünschte Python-Version angeben

    - name: Abhängigkeiten installieren
      run: |
        pip install -r requirements.txt
        python hello.py
    
    - name: Microsoft Teams Notification
      uses: skitionek/notify-microsoft-teams@master
      if: ${{ failure()  || cancelled() }}
      with:
        webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
        needs: ${{ toJson(needs) }}
        job: ${{ toJson(job) }}
        steps: ${{ toJson(steps) }}
        overwrite: "{title: `${{workflow_link}}`}"
        dry_run: False

